version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=db
      - POSTGRES_DB=ravamet
      - SECRET_KEY=change-this-key-in-production-use-openssl-rand-base64-32
    volumes:
      - .:/app
    command: python run.py --reload

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ravamet
    ports:
      - "5432:5432"

volumes:
  postgres_data:
